### ISSUE TITLE
Compute example crashes in create_compute_pipeline

### ISSUE THREAD

**Issue by pbouda** [pygfx/pyshader#48]
**(edit by @Korijn - transferred this issue here from wgpu-py repo)**

I am trying to run the `compute_noop.py` example and get the following error:

```
$ RUST_BACKTRACE=1 python compute_noop.py
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Other', /Users/runner/runners/2.166.2/work/1/s/wgpu/wgpu-core/src/device/mod.rs:1895:17
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_compute_pipeline
  10: ffi_call_unix64
  11: ffi_call_int
  12: cdata_call
  13: _PyObject_MakeTpCall
  14: call_function
  15: _PyEval_EvalFrameDefault
  16: _PyEval_EvalCodeWithName
  17: _PyFunction_Vectorcall
  18: method_vectorcall
  19: call_function
  20: _PyEval_EvalFrameDefault
  21: _PyEval_EvalCodeWithName
  22: _PyFunction_Vectorcall
  23: call_function
  24: _PyEval_EvalFrameDefault
  25: _PyEval_EvalCodeWithName
  26: PyEval_EvalCode
  27: PyRun_FileExFlags
  28: PyRun_SimpleFileExFlags
  29: Py_RunMain
  30: pymain_main
  31: Py_BytesMain
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6
```

How could I debug this further? I am on Mac btw. Any ideas?

**Comment by Korijn** [comment]
Alright, final question: can you share with me which wgpu-native binary you are using? Is there a possibility you are using an outdated binary from when you switched to the latest version of wgpu-py (e.g. forgot to rerun the download script if you were running in development mode)

**Comment by almarklein** [comment]
Mmm. So `GlobalInvocationId` is indeed a ivec3. It looks like on some systems it can be implicitly cast to int, but probably not on all drivers. Will have a look to make sure this is done the correct way.

To make sure that this is the problem, could you try changing the shader in the compute example to:
```py
@python2shader
def compute_shader(
    index: ("input", "GlobalInvocationId", "ivec3"),
    data1: ("buffer", 0, Array(i32)),
    data2: ("buffer", 1, Array(i32)),
):
    data2[index.x] = data1[index.x]
```

**Comment by Korijn** [comment]
Do you have any idea how we could reproduce this @almarklein ? Or is it specific to the machine @pbouda is working with, ou think?

**Comment by almarklein** [comment]
I think this issue is driver-specific.

**Comment by Korijn** [comment]
But if `GlobalInvocationId` is really `ivec3` (or `uvec3`), shouldn't we update our example code and stop relying on a driver feature to do the automatic conversion?

**Comment by pbouda** [comment]
Here are my wgpu-native files, I found them in `site-packages/wgpu/resources/`, I hope that's what you need:

[native.zip](https://github.com/pygfx/pyshader/files/4994147/native.zip)

I think it's the version that came with the Python package, so guess it's recent...?

**Comment by pbouda** [comment]
I also tried to change the example, as you suggested, but then I still get:

```
RUST_BACKTRACE=1 python compute_noop.py
Error compiling the shader CompilationFailed("Compilation failed: \n\nprogram_source:59:5: error: use of undeclared identifier \'_16\'\n    _16._m0[int(gl_GlobalInvocationID.x)] = _12._m0[int(gl_GlobalInvocationID.x)];\n    ^\nprogram_source:59:45: error: use of undeclared identifier \'_12\'\n    _16._m0[int(gl_GlobalInvocationID.x)] = _12._m0[int(gl_GlobalInvocationID.x)];\n                                            ^\n")
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Other', /Users/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/6650b94/wgpu-core/src/device/mod.rs:2119:17
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_compute_pipeline
  10: ffi_call_unix64
  11: ffi_call_int
  12: cdata_call
  13: _PyObject_MakeTpCall
  14: call_function
  15: _PyEval_EvalFrameDefault
  16: _PyEval_EvalCodeWithName
  17: _PyFunction_Vectorcall
  18: method_vectorcall
  19: call_function
  20: _PyEval_EvalFrameDefault
  21: _PyEval_EvalCodeWithName
  22: _PyFunction_Vectorcall
  23: call_function
  24: _PyEval_EvalFrameDefault
  25: _PyEval_EvalCodeWithName
  26: PyEval_EvalCode
  27: PyRun_FileExFlags
  28: PyRun_SimpleFileExFlags
  29: Py_RunMain
  30: pymain_main
  31: Py_BytesMain
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Abort trap: 6
```

**Comment by almarklein** [comment]
Well, we did go from 4 errors to 2:
```
Error compiling the shader CompilationFailed("Compilation failed: 

program_source:59:5: error: use of undeclared identifier \'_16\'
    _16._m0[int(gl_GlobalInvocationID.x)] = _12._m0[int(gl_GlobalInvocationID.x)];
    ^
program_source:59:45: error: use of undeclared identifier \'_12\'
    _16._m0[int(gl_GlobalInvocationID.x)] = _12._m0[int(gl_GlobalInvocationID.x)];
                                            ^
```

**Comment by almarklein** [comment]
It looks like your drives is converting the SpirV to glsl, and in that process it lost the declaration of the storage arrays. I'll see if implementing this snippet in glsl, and compiling that to SpirV produces some SpirV instructions that we could add too ...

**Comment by almarklein** [comment]
All occurrences of `GlobalInvocationID` have been fixed in pyshader, wgpu-py and pygfx.
